#!/bin/sh
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/opt/local/bin
export PATH
export LC_ALL=en_GB.UTF-8

watch -d sh -c 'echo; sysctl -h kstat.spl.misc.spl_misc.vmem_conditional_allocs kstat.spl.misc.spl_misc.ta_xnu_vmem_alloc kstat.spl.misc.spl_misc.ta_xnu_vmem_bytes kstat.spl.misc.spl_misc.ta_xnu_success kstat.spl.misc.spl_misc.ta_xnu_success_bytes kstat.spl.misc.spl_misc.ta_reserve_success kstat.spl.misc.spl_misc.ta_reserve_alloc_bytes kstat.spl.misc.spl_misc.sra_extra_pass kstat.spl.misc.spl_misc.spl_osif_malloc_success kstat.spl.misc.spl_misc.spl_osif_free kstat.vmem.vmem | egrep -v "(: 0$)|\.(lookup|search|mem_total|vmem_source):|(vmem\.vmem\.[^b])"; sysctl -h kstat.vmem.vmem.bucket_heap.mem_total'
